-- PulseBand Supabase Schema
-- Paste this file into the Supabase SQL Editor and run it once.

CREATE TABLE IF NOT EXISTS emergency_settings (
  id INTEGER PRIMARY KEY,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  min_bpm INTEGER NOT NULL DEFAULT 45,
  max_bpm INTEGER NOT NULL DEFAULT 120,
  sustain_samples INTEGER NOT NULL DEFAULT 6,
  cooldown_ms INTEGER NOT NULL DEFAULT 120000,
  auto_dial_webhook_url TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  source_mode TEXT NOT NULL DEFAULT 'sim',
  source_base_url TEXT
);

CREATE TABLE IF NOT EXISTS samples (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  elapsed_ms INTEGER NOT NULL,
  bpm INTEGER NOT NULL,
  filtered_signal INTEGER NOT NULL,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS emergency_contacts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  priority INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS emergency_alerts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER REFERENCES sessions(id) ON DELETE SET NULL,
  level TEXT NOT NULL DEFAULT 'warning',
  reason TEXT NOT NULL,
  bpm INTEGER NOT NULL,
  message TEXT NOT NULL,
  webhook_status TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  acknowledged_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_sessions_started_at ON sessions(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_samples_session_id ON samples(session_id);
CREATE INDEX IF NOT EXISTS idx_samples_recorded_at ON samples(recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_emergency_contacts_priority ON emergency_contacts(priority ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_emergency_alerts_created_at ON emergency_alerts(created_at DESC);

ALTER TABLE emergency_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE samples ENABLE ROW LEVEL SECURITY;
ALTER TABLE emergency_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE emergency_alerts ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  CREATE POLICY "Allow all access to emergency_settings" ON emergency_settings
    FOR ALL USING (true) WITH CHECK (true);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE POLICY "Allow all access to sessions" ON sessions
    FOR ALL USING (true) WITH CHECK (true);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE POLICY "Allow all access to samples" ON samples
    FOR ALL USING (true) WITH CHECK (true);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE POLICY "Allow all access to emergency_contacts" ON emergency_contacts
    FOR ALL USING (true) WITH CHECK (true);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE POLICY "Allow all access to emergency_alerts" ON emergency_alerts
    FOR ALL USING (true) WITH CHECK (true);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

INSERT INTO emergency_settings (id, enabled, min_bpm, max_bpm, sustain_samples, cooldown_ms, auto_dial_webhook_url)
VALUES (1, TRUE, 45, 120, 6, 120000, '')
ON CONFLICT (id) DO NOTHING;
